# Generated by Django 4.1.4 on 2023-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rating_rating_core_rating_content_15cd2e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(verbose_name='ستاره ها'),
        ),
    ]
