# Generated by Django 4.1.4 on 2023-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='کامنت'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(blank=True, null=True, verbose_name='ستاره ها'),
        ),
    ]
