# Generated by Django 4.1.4 on 2022-12-23 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extensions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cats', to='product.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': '2. دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلمات کلیدی')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('stock', models.IntegerField(verbose_name='موجودی در انبار')),
                ('quantity', models.CharField(max_length=50, verbose_name='واحد')),
                ('weight', models.CharField(max_length=100, verbose_name='وزن')),
                ('length', models.CharField(max_length=100, verbose_name='طول')),
                ('width', models.CharField(max_length=100, verbose_name='ضخامت')),
                ('image', models.ImageField(upload_to=extensions.utils.upload_product_image_path, verbose_name='تصویر محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='تائید شده/نشده')),
                ('purchase_limit', models.IntegerField(blank=True, null=True, verbose_name='محدودیت خرید')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('categories', models.ManyToManyField(related_name='products', to='product.category', verbose_name='دسته بندی ها')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_products', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_products', to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': '1. محصولات',
            },
        ),
    ]
