# Generated by Django 4.1.4 on 2022-12-24 17:55

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=extensions.utils.generate_product_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
