# Generated by Django 4.1.4 on 2023-02-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_favoriteproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'ordering': ('-created',), 'verbose_name': 'محصول مورد علاقه', 'verbose_name_plural': '3. محصولات مورد علاقه'},
        ),
    ]
