# Generated by Django 4.1.4 on 2023-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_favoriteproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی'),
        ),
    ]
