# Generated by Django 4.1.4 on 2023-04-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('is_confirmed', models.BooleanField(verbose_name='تائید شده/نشده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تغیر قیمت',
                'verbose_name_plural': '4. تغییرات قیمت',
            },
        ),
    ]
