# Generated by Django 4.2.7 on 2023-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_product_type_product_shops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=136587, max_length=255, verbose_name='اسلاگ'),
        ),
    ]
