# Generated by Django 4.2.7 on 2024-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_contact_subject'),
        ('product', '0016_product_image_url_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(blank=True, null=True, related_name='multiple_products', to='shop.shop', verbose_name='فروشنده ها'),
        ),
    ]
