# Generated by Django 4.2.7 on 2024-03-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خلاصه'),
        ),
    ]
