# Generated by Django 4.2.7 on 2024-06-07 08:07

import ckeditor_uploader.fields
from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=extensions.utils.upload_product_image_path, verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تصویر'),
        ),
        migrations.AddField(
            model_name='category',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='پین شده'),
        ),
        migrations.AddField(
            model_name='category',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
