# Generated by Django 4.1.4 on 2023-01-29 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=155, verbose_name='عنوان')),
                ('summary', models.TextField(max_length=255, verbose_name='خلاصه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر اصلی')),
                ('status', models.CharField(choices=[('a', 'منتشر شده'), ('d', 'چک نویس')], max_length=5, verbose_name='وضعیت انتشار')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('tags', models.ManyToManyField(related_name='articles', to='blog.tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': '2. مقالات',
            },
        ),
    ]
