# Generated by Django 4.1.4 on 2023-01-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_summary_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'چک نویس')], max_length=5, verbose_name='وضعیت انتشار'),
        ),
    ]
