# Generated by Django 4.1.4 on 2023-01-30 15:54

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=extensions.utils.upload_article_image_path, verbose_name='تصویر اصلی'),
        ),
    ]
