# Generated by Django 4.1.4 on 2023-02-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish_time',), 'verbose_name': 'مقاله', 'verbose_name_plural': '2. مقالات'},
        ),
    ]
