# Generated by Django 4.2.7 on 2024-05-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی'),
        ),
    ]
