# Generated by Django 4.1.4 on 2022-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='شناسه اسلاگ'),
        ),
    ]
