# Generated by Django 4.1.4 on 2023-01-28 17:00

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sellerinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='demand',
            field=models.TextField(blank=True, null=True, verbose_name='تقاضا'),
        ),
        migrations.AddField(
            model_name='shop',
            name='supply',
            field=models.TextField(blank=True, null=True, verbose_name='عرضه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=extensions.utils.upload_shop_image_path, verbose_name='تصویر'),
        ),
    ]
