# Generated by Django 4.1.4 on 2023-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_demand_shop_supply_alter_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='unique_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
