# Generated by Django 4.1.4 on 2022-12-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_options_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('r', 'خوانده شده'), ('ur', 'خوانده نشده')], default='ur', max_length=4, verbose_name='وضعیت مشاهده'),
        ),
    ]
