# Generated by Django 4.1.4 on 2023-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_unique_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='unique_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
