# Generated by Django 4.1.4 on 2023-03-26 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_alter_shop_unique_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.BigIntegerField(verbose_name='قیمت')),
                ('sheba', models.CharField(max_length=255, verbose_name='شماره شبا')),
                ('confirmed', models.BooleanField(verbose_name='تائید شده/نشده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='shop.shop', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(verbose_name='مبلغ')),
                ('running_balance', models.BigIntegerField(verbose_name='موجودی بعد از تراکنش')),
                ('transaction_type', models.CharField(choices=[('d', 'واریز'), ('w', 'برداشت')], max_length=2, verbose_name='نوع تراکنش')),
                ('transaction_status', models.BooleanField(verbose_name='وضعیت انجام تراکنش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='shop.wallet', verbose_name='کیف پول')),
            ],
        ),
    ]
