# Generated by Django 4.1.4 on 2023-03-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
