# Generated by Django 4.1.4 on 2023-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': '4. کیف پول ها'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': '5. تراکنش های کیف پول'},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='sheba',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا'),
        ),
    ]
