# Generated by Django 4.1.4 on 2023-03-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_wallet_options_alter_wallettransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ('-created',), 'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': '5. تراکنش های کیف پول'},
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
