# Generated by Django 4.1.4 on 2023-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_wallettransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='تائید شده/نشده'),
        ),
    ]
