# Generated by Django 4.1.4 on 2023-04-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_wallet_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('-created',), 'verbose_name': 'کیف پول', 'verbose_name_plural': '4. کیف پول ها'},
        ),
    ]
