# Generated by Django 4.1.4 on 2023-07-01 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_alter_wallet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInvoice',
            fields=[
                ('id', models.CharField(default=extensions.utils.generate_product_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='نشانی')),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('tax', models.BigIntegerField(default=0, verbose_name='مالیات')),
                ('discount', models.BigIntegerField(default=0, verbose_name='تخفیف')),
                ('invoice_shop', models.CharField(choices=[('pre', 'پیش فاکتور'), ('sales', 'فاکتور فروش')], max_length=20, verbose_name='تایپ فاکتور')),
                ('life_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ اعتبار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_invoices', to='shop.shop', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_invoices', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
            ],
            options={
                'verbose_name': 'فاکتور فروشگاه',
                'verbose_name_plural': '6. فاکتور های فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ShopInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='نام')),
                ('quantity', models.BigIntegerField(default=1, verbose_name='مقدار')),
                ('quantity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد')),
                ('amount', models.BigIntegerField(verbose_name='قیمت')),
                ('count_of_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='تعداد')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='shop.shopinvoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'جزئیات فاکتور',
                'verbose_name_plural': '7. جزئیات فاکتور ها',
            },
        ),
    ]
