# Generated by Django 4.1.4 on 2023-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shopinvoice_shopinvoicedetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopinvoice',
            options={'ordering': ('-created',), 'verbose_name': 'فاکتور فروشگاه', 'verbose_name_plural': '6. فاکتور های فروشگاه'},
        ),
        migrations.AddField(
            model_name='shopinvoice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح فاکتور'),
        ),
    ]
