# Generated by Django 4.1.4 on 2023-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_shopinvoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinvoice',
            name='transport_cost',
            field=models.BigIntegerField(default=0, verbose_name='کرایه باربری'),
        ),
    ]
