# Generated by Django 4.1.4 on 2023-07-06 09:28

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_shopinvoice_transport_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinvoice',
            name='life_time',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ اعتبار'),
        ),
    ]
