# Generated by Django 4.1.4 on 2023-07-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_shopinvoice_life_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='score',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
