# Generated by Django 4.1.4 on 2023-02-07 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_favoriteproduct_options'),
        ('shop', '0003_shop_demand_shop_supply_alter_shop_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=extensions.utils.generate_order_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': '1. سفارشات',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created',), 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.BigIntegerField(blank=True, null=True, verbose_name='هزینه حمل و نقل')),
                ('status', models.CharField(choices=[('posted', 'ارسال شده'), ('pending', 'درحال بررسی'), ('returned', 'برگشت خورده'), ('confirmed', 'تائید شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_transfers', to='cart.order', verbose_name='سفارش')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportations', to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'حمل و نقل',
                'verbose_name_plural': '2. حمل و نقل ها',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('price', models.BigIntegerField(verbose_name='قیمت در زمان خرید')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='تائید شده/نشده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='cart.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول در سفارش',
                'verbose_name_plural': '4. محصولات در سفارش',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.address', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
