# Generated by Django 4.1.4 on 2023-02-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_alter_address_options_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created',), 'verbose_name': 'آدرس', 'verbose_name_plural': '5. آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'سفارش', 'verbose_name_plural': '1. سفارشات'},
        ),
    ]
