# Generated by Django 4.1.4 on 2023-03-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_address_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportation',
            options={'ordering': ('-id',), 'verbose_name': 'حمل و نقل', 'verbose_name_plural': '2. حمل و نقل ها'},
        ),
    ]
