# Generated by Django 4.1.4 on 2023-04-10 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('d', 'چک نویس'), ('p', 'منتشر شده')], max_length=10, verbose_name='وضعیت')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('address', models.CharField(blank=True, max_length=75, null=True, verbose_name='مکان')),
                ('date', models.CharField(blank=True, max_length=75, null=True, verbose_name='تاریه اجرا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': '1. نمونه کار ها',
            },
        ),
        migrations.CreateModel(
            name='WorkSampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='تصویر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('work_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='metallurgy.worksample', verbose_name='نمونه کار')),
            ],
            options={
                'verbose_name': 'تصویر نمونه کار',
                'verbose_name_plural': '1. تصاویر نمونه کار',
            },
        ),
    ]
