# Generated by Django 4.1.4 on 2023-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksampleimage',
            options={'verbose_name': 'تصویر نمونه کار', 'verbose_name_plural': '2. تصاویر نمونه کار'},
        ),
        migrations.AlterField(
            model_name='worksample',
            name='date',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='تاریخ اجرا'),
        ),
    ]
