# Generated by Django 4.1.4 on 2023-04-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0003_invoice_project_invoicedetail_invoice_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={'verbose_name': 'جزئیات فاکتور', 'verbose_name_plural': '5. جزئیات فاکتور'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت تسویه'),
        ),
    ]
