# Generated by Django 4.1.4 on 2023-04-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0004_alter_invoicedetail_options_project_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',), 'verbose_name': 'پروژه', 'verbose_name_plural': '3. پروژه ها'},
        ),
    ]
