# Generated by Django 4.1.4 on 2023-04-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0006_projecttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_transaction', to='metallurgy.invoice', verbose_name='فاکتور'),
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='metallurgy.project', verbose_name='پروژه'),
        ),
    ]
