# Generated by Django 4.1.4 on 2023-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0007_projecttransaction_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttransaction',
            options={'ordering': ('-created',), 'verbose_name': 'تراکنش', 'verbose_name_plural': '6. تراکنش های پروژه'},
        ),
        migrations.AlterField(
            model_name='projecttransaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
