# Generated by Django 4.1.4 on 2023-06-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0008_alter_projecttransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='quantity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد'),
        ),
    ]
