# Generated by Django 4.1.4 on 2023-07-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0011_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={'ordering': ('created',), 'verbose_name': 'جزئیات فاکتور', 'verbose_name_plural': '5. جزئیات فاکتور'},
        ),
    ]
