# Generated by Django 4.1.4 on 2023-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0012_alter_invoicedetail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='show_stamp',
            field=models.BooleanField(default=True, verbose_name='نمایش مهر'),
        ),
    ]
