# Generated by Django 4.2.7 on 2023-12-09 18:13

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_product_type_product_shops_and_more'),
        ('metallurgy', '0013_invoice_show_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksample',
            name='categories',
            field=models.ManyToManyField(related_name='portfolios', to='product.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='worksample',
            name='customer',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='کارفرما'),
        ),
        migrations.AddField(
            model_name='worksample',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='worksampleimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=extensions.utils.upload_portfolio_image_path, verbose_name='فایل-ویدئو'),
        ),
        migrations.AlterField(
            model_name='worksampleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=extensions.utils.upload_portfolio_image_path, verbose_name='تصویر'),
        ),
    ]
