# Generated by Django 4.2.7 on 2023-12-09 18:17

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0014_worksample_categories_worksample_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksampleimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=extensions.utils.upload_portfolio_image_path, verbose_name='فایل-ویدئو'),
        ),
    ]
