# Generated by Django 4.2.7 on 2023-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0015_alter_worksampleimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksample',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خلاصه'),
        ),
    ]
