# Generated by Django 4.2.7 on 2023-12-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0017_alter_worksample_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksample',
            options={'ordering': ('-publish_time',), 'verbose_name': 'نمونه کار', 'verbose_name_plural': '1. نمونه کار ها'},
        ),
    ]
