# Generated by Django 4.2.7 on 2024-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metallurgy', '0018_alter_worksample_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksample',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان متا'),
        ),
        migrations.AlterField(
            model_name='worksample',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
